name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Determine VITE_BASE_PATH
        run: |
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          OWNER="${GITHUB_REPOSITORY_OWNER}"
          if [ "${REPO_NAME}" = "${OWNER}.github.io" ]; then
            echo "VITE_BASE_PATH=/" >> "$GITHUB_ENV"
          else
            echo "VITE_BASE_PATH=/${REPO_NAME}/" >> "$GITHUB_ENV"
          fi
        shell: bash

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_BASE_PATH: ${{ env.VITE_BASE_PATH }}
        run: npm run build

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
